spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:in-mem
   # tcp: jdbc:h2:tcp://localhost:9092/mem
    username: admin
    password: admin
jwt:
  sessionTime: 120000000
  secret: secret_key